[build]
  command = "pnpm install && pnpm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/_next/data/*"
  to = "/_next/data/:splat"
  status = 200
